version: '3.8'
services:
  s-bank-staging:
    image: mohammadnowresideh1997/s-bank-staging
    env_file:
      - /root/config/s-bank-staging.env.txt
    container_name: s-bank-staging
    restart: always
    ports:
      - 3003:3003
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
