version: '3.8'
services:
  s-bank-prod:
    image: ${DOCKER_USERNAME}/s-bank-prod
    env_file:
      - /root/config/s-bank-prod.env.txt
    container_name: s-bank-prod
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
